const variables = {
  FILMS_TITLES: [`Reservoir Dogs`, `Pulp Fiction`, `The Grand Budapest Hotel`, `No Country for Old Men`, `Fargo `, `Durak`, `The Big Lebowski`, `Inglourious Basterds`, `Once Upon a Time... in Hollywood`, `Knockin' on Heaven's Door`, `Blade Runner`, `Se7en`, `Sen to Chihiro no kamikakushi`, `Kurenai no buta`, `Mononoke-hime`, `Isle of Dogs`, `Fantastic Mr. Fox`, `Schindler's List`, `Snatch`, `Lock, Stock and Two Smoking Barrels`, `In Bruges`, `Three Billboards Outside Ebbing, Missouri`],
  FILMS_POSTERS: [`images/posters/made-for-each-other.png`, `images/posters/popeye-meets-sinbad.png`, `images/posters/sagebrush-trail.jpg`, `images/posters/santa-claus-conquers-the-martians.jpg`, `images/posters/the-dance-of-life.jpg`, `images/posters/the-great-flamarion.jpg`, `images/posters/the-man-with-the-golden-arm.jpg`],
  TEXT_MOCKS: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras aliquet varius magna, non porta ligula feugiat eget. Fusce tristique felis at fermentum pharetra. Aliquam id orci ut lectus varius viverra. Nullam nunc ex, convallis sed finibus eget, sollicitudin eget ante. Phasellus eros mauris, condimentum sed nibh vitae, sodales efficitur ipsum. Sed blandit, eros vel aliquam faucibus, purus ex euismod diam, eu luctus nunc ante ut dui. Sed sed nisi sed augue convallis suscipit in sed felis. Aliquam erat volutpat. Nunc fermentum tortor ac porta dapibus. In rutrum ac purus sit amet tempus.`,
  GENRES: [`Action`, `Blockbuster`, `Sci-Fi`, `Fantasy`, `Musical`, `Western`, `Romantic`, `Adventure`, `Horror`, `Thriller`, `Mystery`, `Drama`, `Crimes`],
  AUTHORS: [`Jack Sparrow`, `Casper`, `John Doe`, `Michael`, `PussyCracker`, `Kraken`, `Roman`, `Honey Bunny`, `King Arthur`, `Bart Simpson`],
  COMMENTS: [`Interesting setting and a good cast`, `Booooooooooring`, `Very very old. Meh`, `AlmosRt two hours? Seriously?`],
  EMOJIS: [`smile`, `sleeping`, `puke`, `angry`],
  RATINGS: [`0`, `6+`, `12+`, `16+`, `18+`],
  DIRECTORS: [`Tom Ford`, `Quentin Tarantino`, `Wes Anderson`, `Hayao Miyazaki`, `Martin McDonagh`, `Guy Ritchie`, `Joel Coen & Ethan Coen`, `Ridley Scott`, `Thomas Jahn`, `David Fincher`, `Steven Spielberg`],
  ACTORS: [`Ralph Fiennes`, `Willem Dafoe`, `Edward Norton`, `Tilda Swinton`, `Ben Kingsley`, `Leonardo DiCaprio`, `Tom Hanks`, `Christopher Walken`, `Sam Rockwell`, `Woody Harrelson`, `Colin Farrell`, `Brendan Gleeson`, `Vinnie Jones`, `Matthew McConaughey`, `Charlie Hunnam`],
  COUNTRIES: [`USA`, `England`, `France`, `Germany`, `Spain`, `Czech`],
  SUGGESTIONS_COUNT: 5,
  MAX_RATING: 10,
  MIN_RATING: 1,
  MAX_DURATION: 140,
  MIN_DURATION: 35,
  MAX_GENRES: 5,
  MIN_GENRES: 1,
  MIN_DESCRIPTION: 1,
  MAX_COMMENTS: 14,
  MIN_COMMENTS: 0,
  MAX_WRITERS: 2,
  MIN_WRITERS: 1,
  MAX_ACTORS: 5,
  MIN_ACTORS: 1,
  MAX_COUNTRY: 3,
  MIN_COUNTRY: 1,
  MAX_FILM_CARD: 20,
  MAX_DAYS_GAP: 1250,
  MAX_HOURS_GAP: 14,
  MIN_IN_HOUR: 60,
  MAX_SYMBOL_IN_DESCRIPTION: 139,
  HOUR_FORMAT: `h`,
  MINUTE_FORMAT: `m`,
  SHORT_DATE_OPTIONS: {year: `numeric`},
  FULL_DATE_OPTIONS: {day: `2-digit`, month: `long`, year: `numeric`},
  COMMENT_DATE_OPTIONS: {minute: `2-digit`, hour12: false, hour: `2-digit`},
  SECOND_IN_DAY: 86400,
};

export {variables};
